### PR TITLE
[WIP] Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**
- Use GZDoom from shared-modules.
- Update the runtime to 22.08.
- Update dependencies.

Still not ready to be merged. See [this comment](https://github.com/flathub/com.moddb.TotalChaos/pull/11#issuecomment-1260969237).

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
`Failed to download sources: module totalchaos: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)`

Hmm, this looks like a HTTP/2 bug to me. The url works fine for me when trying to manually download the archive using Firefox or wget. I wonder whether there is any way to force HTTP/1.1 in the Flatpak manifest.

@nedrichards Any idea?

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
Still the same strange problem.

/cc @barthalion @nedrichards

**Comment by AsciiWolf** [comment]
```
$ curl -L https://www.dropbox.com/sh/93rt8tqpn3i44zp/AAArEDsQrEz5ntHCF2QZz3GLa/totalchaos_dc_b3.zip?dl=1 --output totalchaos_dc_b3.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154    0   154    0     0    387      0 --:--:-- --:--:-- --:--:--   387
100   342  100   342    0     0    403      0 --:--:-- --:--:-- --:--:--     0
  2 1224M    2 25.6M    0     0  1909k      0  0:10:56  0:00:13  0:10:43 2078k^C
```

Both wget and curl work fine when downloading the file manually on my system.

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
bot, build

**Comment by barthalion** [comment]
The canonical URL for Total Chaos I found via Google seems to be ModDB. Any reason not to use `https://www.moddb.com/downloads/mirror/207439/128/4c7f7b58c24fd813deb4d056561bc120`, or is that URL generated dynamically? If yes, I would just abuse GitHub and upload it as "release artifact" of a fake tag.

**Comment by AsciiWolf** [comment]
Yep, the ModDB download URL seems to be generated dynamically. The Dropbox link is an official upload from Total Chaos developer. I am not sure whether it is possible to upload a file this big (over 1GB) to GitHub.

**Comment by barthalion** [comment]
Is the developer fine if we re-host it elsewhere, e.g. on our own infra?

**Comment by AsciiWolf** [comment]
I will try asking, but if I remember correctly, he had no issues with it.

**Comment by barthalion** [comment]
I've mirrored it at `https://dl.flathub.org/sources/com.moddb.TotalChaos/totalchaos_dc_b3.zip`.

**Comment by AsciiWolf** [comment]
Thanks!

**Comment by AsciiWolf** [comment]
The aspect ratio/resolution of game UI and even some ingame textures seems to be incorrect when using more recent GZDoom. This makes the game look bad. It looks like that something from the Total Chaos custom gzdoom config file is not supported by GZDoom anymore. Sadly, the old GZDoom version does not build with newer fd runtime (I have tried to workaround it, but no luck).
Also, save games from older Total Chaos build do not seem to be compatible with the new build because of updated GZDoom.

**Pull request closed without merging**
