### PR TITLE
Update GZDoom, FluidSynth and Soundfonts

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
bot, build

**Comment by Alexander-Wilms** [comment]
GZDoom now uses asmjit, which doesn't support ARM. See https://github.com/flathub/io.github.Freedoom-Phase-1/issues/9

**Comment by AsciiWolf** [comment]
bot, build

**Pull request merged**
